## Exercice 1

1. Combien y a-t-il de tables dans la base de données ?

Une seule table, `prix`.

2. Quelle est la clef primaire ?

La clef primaire est le champ `pk`.

3.Combien y a-t-il de lignes (enregistrements) ?

In [1]:
SELECT COUNT(*) FROM prix

COUNT(*)
26940

4. Quel est le domaine du champ `prix_valeur` ?

DB Browser dor SQLite permet d'accéder à la structure de la table `prix`. Ici, on utiliser une commande SQLite hors-programme.

In [ ]:
PRAGMA table_info('prix');

Le domaine est `REAL` : c'est un nombre réel.

5. Quelle est la différence entre les champs `com\_name` et `com\_arm\_name` ?

In [ ]:
SELECT com_arm_name,com_name 
FROM prix 
WHERE com_arm_name<>com_name

`com_arm_name` contient le numéro d'arrondissement pour Paris, Lyon et Marseille.

## Exercice 2

1. Écrire une requête SQL qui donne pour chaque station : la ville, l'adresse, le type de carburant et le prix correspondant.

In [ ]:
SELECT ville, adresse, prix_nom, prix_valeur
FROM prix

2. Écrire une requête SQL qui donne la liste des villes, adresses et prix du sans plomb 95 pour les  stations de Saône-et-Loire. Les trier par prix croissant.

In [ ]:
SELECT ville, adresse, prix_valeur
FROM prix
WHERE prix_nom="SP95" AND dep_name="Saône-et-Loire"
ORDER BY prix_valeur ASC

3. Écrire une requête SQL qui donne les communes et le numéro de département des stations proposant du E85 en Bourgogne-Franche-Comté. On ne veut chaque commune qu'une fois.

In [ ]:
SELECT DISTINCT com_name, dep_code
FROM prix
WHERE reg_name="Bourgogne-Franche-Comté" AND prix_nom="E85"

4. Écrire une requête SQL qui donne la liste des villes où on trouve du E10 à un prix supérieur à $2$ € par litre. Trier par ordre alphabétique.

In [ ]:
SELECT DISTINCT ville
FROM prix
WHERE prix_nom="E10" AND prix_valeur>=2
ORDER BY ville

5. Écrire une requête SQL qui renvoie les $10$ stations les plus chères de France en gazole hors Paris, les trier par prix décroissant.

In [ ]:
SELECT ville, adresse
FROM prix
WHERE prix_nom="Gazole" AND com_name<>"Paris"
ORDER BY prix_valeur DESC
LIMIT 10

## Exercice 3

1. Écrire une requête SQL qui renvoie le prix moyen en France pour chaque carburant ; nommer « prix moyen » la colonne de prix.

In [ ]:
SELECT prix_nom,AVG(prix_valeur) AS "prix moyen"
FROM prix
GROUP BY prix_nom
ORDER BY "prix moyen"

2. Écrire une requête SQL qui renvoie le prix maximal du sans plomb 98 par région.

In [ ]:
SELECT reg_name,MAX(prix_valeur)
FROM prix
WHERE prix_nom="SP98"
GROUP BY reg_name

3. Écrire une requête SQL qui renvoie les 20 stations où l'écart entre le carburant le plus cher et le moins cher est le plus grand.

In [ ]:
SELECT adresse, ville, MAX(prix_valeur)-MIN(prix_valeur) AS ecart
FROM prix
GROUP BY id
ORDER BY ecart DESC
LIMIT 20

4. Écrire une requête SQL qui renvoie la liste des stations qui proposent au plus deux carburants (il y a pénurie !)

In [ ]:
SELECT ville, adresse
FROM prix
GROUP BY id
HAVING COUNT(prix_nom)<=2

5. Écrire une requête SQL qui renvoie la liste des départements où le prix moyen du gazole est supérieur à la moyenne nationale.

In [3]:
SELECT dep_name, AVG(prix_valeur) as "prix moyen"
FROM prix
WHERE prix_nom="Gazole" 
GROUP BY dep_name
HAVING AVG(prix_valeur)>= (SELECT AVG(prix_valeur) FROM prix WHERE prix_nom="Gazole")

dep_name	prix moyen
Aisne	1.897324324324324
Allier	1.8939838709677421
Alpes-Maritimes	1.8728536585365854
Ardennes	1.9139722222222224
Aube	1.8963454545454546
Cantal	1.8818775510204082
Cher	1.9003272727272726
Corrèze	1.874551724137931
Creuse	1.8769
Côte-d'Or	1.8864716981132077
Dordogne	1.867012048192771
Doubs	1.8922926829268294
Essonne	1.9089716981132074
Eure-et-Loir	1.8773965517241378
Haute-Marne	1.9242045454545456
Haute-Savoie	1.8715504587155962
Haute-Saône	1.891255319148936
Haute-Vienne	1.8848666666666667
Hautes-Pyrénées	1.88795
Hauts-de-Seine	1.9433833333333335
Indre	1.8654666666666666
Indre-et-Loire	1.8779863013698628
Jura	1.9021492537313434
Landes	1.8796354166666667
Loir-et-Cher	1.9109622641509436
Loiret	1.8775510204081634
Lot	1.8728823529411764
Lozère	1.8894864864864864
Marne	1.9064507042253522
Meurthe-et-Moselle	1.9100400000000002
Meuse	1.8804814814814816
Moselle	1.8896517857142856
Nièvre	1.9341538461538463
Oise	1.8632470588235295
Orne	1.8739473684210526
Paris	1.993238095238095
Sarthe	1.879525
Savoie	1.8759397590361446
Saône-et-Loire	1.8841929824561403
Seine-Saint-Denis	1.914703125
Seine-et-Marne	1.8916950354609927
Somme	1.8835742574257428
Territoire de Belfort	1.9075833333333334
Val-d'Oise	1.8939390243902439
Val-de-Marne	1.9290634920634921
Vosges	1.887722222222222
Yonne	1.9032933333333335
Yvelines	1.893878787878788